# Generated by Django 6.0.1 on 2026-02-14 17:47

import django.db.models.deletion
import expeditions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animal_slug_alter_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=150, validators=[expeditions.validators.validate_text])),
                ('expected_species', models.ManyToManyField(blank=True, related_name='expected_expeditions', to='animals.animal')),
                ('target_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_expeditions', to='animals.animal')),
            ],
        ),
    ]
