# Generated by Django 6.0.1 on 2026-01-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kingdom', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=100)),
                ('most_distinctive_feature', models.CharField(max_length=150)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
    ]
