# Generated by Django 6.0.1 on 2026-01-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='expeditions/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='animals.animal')),
                ('location', models.ManyToManyField(blank=True, related_name='expeditions', to='locations.location')),
            ],
        ),
    ]
