# Generated by Django 6.0.1 on 2026-02-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='animal',
        ),
        migrations.AddField(
            model_name='expedition',
            name='additional_animals',
            field=models.ManyToManyField(blank=True, related_name='additional_expeditions', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='primary_animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_expeditions', to='animals.animal'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='location',
        ),
        migrations.AddField(
            model_name='expedition',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
