# Generated by Django 6.0.1 on 2026-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedition',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
