# Generated by Django 6.0.1 on 2026-02-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_remove_expedition_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
