# Generated by Django 6.0.1 on 2026-02-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_slug_alter_animal_name'),
        ('expeditions', '0003_expedition_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='additional_animals',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='animal_image',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='primary_animal',
        ),
        migrations.AddField(
            model_name='expedition',
            name='expected_species',
            field=models.ManyToManyField(blank=True, related_name='expected_expeditions', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='target_species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_expeditions', to='animals.animal'),
            preserve_default=False,
        ),
    ]
