# Generated by Django 6.0.1 on 2026-02-11 12:13

import expeditions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0004_remove_expedition_additional_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='location',
            field=models.CharField(max_length=150, validators=[expeditions.validators.validate_text]),
        ),
    ]
