# Generated by Django 6.0.1 on 2026-02-14 17:49

import django.db.models.deletion
import sightings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animal_slug_alter_animal_name'),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at_date', models.DateField()),
                ('observed_at_time', models.TimeField()),
                ('count', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[sightings.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[sightings.validators.validate_longitude])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='sightings/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='animals.animal')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='expeditions.expedition')),
            ],
        ),
    ]
